apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: rajeshwar2473/nextjs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URI

            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLERK_SECRET_KEY

            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
