apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: rajeshwar2473/nextjs-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secret
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

            ✅ - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-secret
                  key: CLERK_SECRET_KEY
